apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    templates:
    - '/etc/alertmanager/secrets/*-tmpl-secrets/secrets'
    - '/etc/alertmanager/configmaps/*-templates/templates'

    route:
      group_by:
        - namespace
        - alertname
        - cluster
        - severity
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 1h
      routes:
        - match:
            alertname: Watchdog
          receiver: Watchdog

    inhibit_rules:
      - equal:
          - namespace
          - alertname
          - cluster
        source_match:
          severity: critical
        target_match_re:
          severity: warning|info
      - equal:
          - namespace
          - alertname
          - cluster
        source_match:
          severity: warning
        target_match_re:
          severity: info

    receivers:
      - name: Default
        pagerduty_configs:
        - send_resolved: true
          routing_key: '{{ template "pagerduty.sre.integrationKey" }}'
          url: https://events.pagerduty.com/v2/enqueue
          client: '{{ template "myorg.pagerduty.client" . }}'
          client_url: '{{ template "myorg.pagerduty.clientURL" . }}'
          description: '{{ template "myorg.pagerduty.description" .}}'
          details:
            firing: '{{ template "myorg.pagerduty.instances" .Alerts.Firing }}'
            num_firing: '{{ .Alerts.Firing | len }}'
            num_resolved: '{{ .Alerts.Resolved | len }}'
            resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
          severity: '{{ template "myorg.pagerduty.severity" . }}'
          class: SampleClassFromAlertmanager
          component: '{{ if .GroupLabels.component }}{{.GroupLabels.component}}{{ else }}None{{
            end }}'
          group: '{{ if .GroupLabels.k8s_cluster }}{{.GroupLabels.k8s_cluster}}{{ else }}None{{
            end }}'
      - name: Watchdog
type: Opaque
