apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.31.1
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: prometheus
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/part-of: kube-prometheus
              prometheus: k8s
          namespaces:
          - monitoring
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  enableFeatures: []
  externalLabels:
    cluster: someCluster
    instance: k8s
  externalUrl: http://192.168.39.69:30900
  image: quay.io/prometheus/prometheus:v2.31.1
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.31.1
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      prometheus: k8s
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      prometheus: k8s
  replicas: 1
  resources:
    limits:
      cpu: 2500m
      memory: 4000Mi
    requests:
      cpu: 150m
      memory: 400Mi
  retention: 24h
  retentionSize: 500MB
  ruleNamespaceSelector: {}
  ruleSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - k8s
    - key: role
      operator: In
      values:
      - alert-rules
      - recording-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: k8s
  version: 2.31.1
