apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.31.1
    prometheus: istio
  name: prometheus-istio
  namespace: monitoring
spec:
  ports:
  - name: web
    nodePort: 30901
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: istio
  sessionAffinity: ClientIP
  type: NodePort
